version: 2
project_name: devx
before:
  hooks:
    - go test ./...

builds:
  - id: devx
    main: ./main.go
    binary: devx
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/jfox85/devx/version.Version={{.Version}}
      - -X github.com/jfox85/devx/version.GitCommit={{.ShortCommit}}
      - -X github.com/jfox85/devx/version.BuildDate={{.Date}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    wrap_in_directory: false

changelog:
  use: git

brews:
  - name: devx
    homepage: https://github.com/jfox85/devx
    description: "A macOS development environment manager"
    license: "MIT"
    commit_author:
      name: devx-bot
      email: devx@jonefox.com
    repository:
      owner: jfox85
      name: homebrew-devx
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    test: |
      system "#{bin}/devx", "--version"
    install: |
      bin.install "devx"

announce:
  skip: true
