session_name: jf-test-harness
start_directory: /Users/jfox/projects/devx/.worktrees/jf-test-harness
suppress_history: false
options:
  base-index: 1
  automatic-rename: "off"
windows:
  - window_name: editor
    layout: tiled
    shell_command_before:
      - cd /Users/jfox/projects/devx/.worktrees/jf-test-harness
      - export SESSION_NAME=jf-test-harness
    panes:
      - claude

  - window_name: repo-root
    layout: tiled
    shell_command_before:
      - cd /Users/jfox/projects/devx/.worktrees/jf-test-harness
      - export SESSION_NAME=jf-test-harness    
    panes:
      - cd /Users/jfox/projects/devx/.worktrees/jf-test-harness

