package backuprestore

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// RewriteResult reports the fixture-only config copies (counts only).
type RewriteResult struct {
	SessionsRewritten  int  `json:"sessions_rewritten"`
	ProjectsRewritten  int  `json:"projects_rewritten"`
	RealPathRefsAfter  int  `json:"real_path_references_after_rewrite"`
	ConfigSanitized    bool `json:"config_sanitized"`
	AllowlistSynthetic bool `json:"allowlist_synthetic"`
}

// RewriteForFixture builds a fixture-only DevX config dir at
// <root>/home/.config/devx from the restored data copies:
//
//   - sessions.json and projects.json are parsed and every absolute path
//     that pointed under realHome is remapped under <root>/mapped/...;
//   - config.yaml is NOT copied (it contains real tokens, domains and
//     service settings). A fresh minimal config is written instead, with
//     caddy/updates/web autostart disabled and a synthetic pi_mcp allowlist;
//   - nothing is executed.
//
// The original restored data under <root>/restored is left untouched for
// hash comparison.
func RewriteForFixture(root, realHome string, allowProject string) (*RewriteResult, error) {
	if !filepath.IsAbs(realHome) || realHome == "/" {
		return nil, rejectf("real home %q invalid", realHome)
	}
	src := filepath.Join(root, "restored", "files", strings.TrimPrefix(realHome, "/"), ".config", "devx")
	dst := filepath.Join(root, "home", ".config", "devx")
	if !within(dst, root) {
		return nil, rejectf("destination escapes fixture")
	}
	if err := os.MkdirAll(dst, 0o700); err != nil {
		return nil, err
	}
	mapped := filepath.Join(root, "mapped")
	remap := func(s string) string {
		if s == realHome || strings.HasPrefix(s, realHome+"/") {
			return filepath.Join(mapped, strings.TrimPrefix(s, "/"))
		}
		if strings.HasPrefix(s, "/") && !strings.HasPrefix(s, root) {
			// Any other absolute path (e.g. /tmp/..., /workspace) is also
			// confined.
			return filepath.Join(mapped, "abs", strings.TrimPrefix(s, "/"))
		}
		return s
	}
	res := &RewriteResult{}
	for _, name := range []string{"sessions.json", "projects.json"} {
		data, err := os.ReadFile(filepath.Join(src, name))
		if err != nil {
			return nil, fmt.Errorf("read restored %s: %w", name, err)
		}
		var v any
		if err := json.Unmarshal(data, &v); err != nil {
			return nil, fmt.Errorf("parse restored %s: %w", name, err)
		}
		v = walkStrings(v, remap)
		if m, ok := v.(map[string]any); ok {
			for _, key := range []string{"sessions", "projects"} {
				if inner, ok := m[key].(map[string]any); ok {
					if name == "sessions.json" {
						res.SessionsRewritten = len(inner)
					} else {
						res.ProjectsRewritten = len(inner)
					}
				}
			}
		}
		out, _ := json.MarshalIndent(v, "", "  ")
		if bytes.Contains(out, []byte(`"`+realHome+"/")) || bytes.Contains(out, []byte(`"`+realHome+`"`)) {
			return nil, rejectf("%s still references the real home after rewrite", name)
		}
		if err := os.WriteFile(filepath.Join(dst, name), out, 0o600); err != nil {
			return nil, err
		}
	}
	cfg := fmt.Sprintf(`# Fixture-only DevX config generated by backuprestore. Not the real config.
basedomain: localhost
disable_caddy: true
target: host
ports: []
auto_check_updates: false
web_autostart: false
usage:
  enabled: false
pi_mcp:
  allowed_projects: [%s]
`, strconv.Quote(allowProject))
	if err := os.WriteFile(filepath.Join(dst, "config.yaml"), []byte(cfg), 0o600); err != nil {
		return nil, err
	}
	res.ConfigSanitized, res.AllowlistSynthetic = true, true
	n, err := countRefs(filepath.Join(root, "home"), realHome)
	if err != nil {
		return nil, err
	}
	res.RealPathRefsAfter = n
	return res, nil
}

func walkStrings(v any, f func(string) string) any {
	switch t := v.(type) {
	case string:
		return f(t)
	case []any:
		for i := range t {
			t[i] = walkStrings(t[i], f)
		}
		return t
	case map[string]any:
		keys := make([]string, 0, len(t))
		for k := range t {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		out := make(map[string]any, len(t))
		for _, k := range keys {
			out[f(k)] = walkStrings(t[k], f)
		}
		return out
	}
	return v
}

func countRefs(dir, needle string) (int, error) {
	n := 0
	err := filepath.Walk(dir, func(p string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		data, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		// Count values that START with the real home (quoted JSON/YAML
		// strings or bare YAML values); remapped paths embed it only after
		// the fixture prefix.
		for _, pre := range []string{`"`, `'`, ": ", "- ", "\n"} {
			n += bytes.Count(data, []byte(pre+needle+"/"))
			n += bytes.Count(data, []byte(pre+needle+`"`))
		}
		if bytes.HasPrefix(data, []byte(needle+"/")) {
			n++
		}
		return nil
	})
	return n, err
}
